
# travis config

dist: bionic
language: r
sudo: required

addons:
  apt:
    packages:
      - libxml2-dev

r:
 - release

before_install:
  - R -e "install.packages(c('validate','settings','pkgload','roxygen2','tinytest','knitr','lumberjack'))"
  - make doc
  - make pkg/vignettes/jss3483.pdf
  - cd ./pkg

r_packages:
  - covr
  - rmarkdown


after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


